### ISSUE TITLE
Helpful Development Plugins

### ISSUE THREAD

**Issue by caroham29** [Shift3/standards-and-practices#231]
**Is your feature request related to a problem? Please describe.**
A list of your most helpful web plugins

**Describe the solution you'd like**
A helpful list of safe plugins we've found to be helpful while developing.

Some common web plugins for React Development:

- [React Developer Tools](https://github.com/facebook/react/tree/master/packages/react-devtools-extensions)
- [Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension)

If you know of any others feel free to add them!

**Comment by Karvel** [comment]
I have a list I wrote up a while back for my recommended Visual Studio Code Extensions:

# Visual Studio Code

## Recommended Extensions

- [GitLens — Git supercharged - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
Awesome parsing of the project's git information. Allows you to see history and blame within the project, and can show you git history on the line you highlight.
- [Bracket Pair Colorizer 2 - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2)
Makes nested brackets have different colors.
- [change-case - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case)
And easy way to change the case of selected text.
- [Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
A regular spell checker. It's smart enough to parse each part of camel/pascal case separately.
- [IntelliSense for CSS class names in HTML - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)
Autocompletion for CSS names based on existing rules.
- [Path Intellisense - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
Path autocompletions.
- [Debugger for Chrome - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
Debugger. Essential.
- [Docker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
Useful tooling if you use Docker.
- [ESLint - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
The de facto Javascript linter.
- [Excel Viewer - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer)
Can parse CSV as a table.
- [Live Server - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
An easy way to launch a server from your project.
- [Todo Tree - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)
Helps organize TODOs so they don't get lost.
- [Live Share Extension Pack - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack)
LiveShare extension pack. The paired programming tool of choice at Shift3.

### Angular

- [Angular Essentials (Version 9) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=johnpapa.angular-essentials)
A pack of extensions maintained by one of the "celebrities" in the Angular world.

### Settings

In addition to the above extensions, I have some settings I configure in Visual Studio Code:

- Turn on Codelens for Javascript and Typescript. This parses your projects for class, method, and property references and shows them above the class/method/property declaration. It does cause slight slowdown when loading a file, but I consider it a worthy tradeoff.
- Turn on breadcrumbs. These show file path breadcrumbs above the editor window.

**Comment by codysmith287** [comment]
@Karvel Awesome list! I was just thinking of putting together a list of fairly nonopinionated and helpful extensions for Visual Studio exactly like this one.

What do you think about [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)?  

I know Prettier is _pretty_ opinionated, but I like that it saves time and attention on formatting. It is lazy? Ehh... yeah, probably. A couple of things I would recommend one do if using Prettier in your Visual Studio Code settings would be:
1) Have Prettier formatting run on each time you save a file rather than run as an npm script.
![image](https://user-images.githubusercontent.com/20328572/104073934-c75a7980-51c3-11eb-8a40-a27ace8ed2ba.png)
2) Have Prettier format **only** if a Prettier config file (`.prettierrc`) exists in the root directory of a project. That way if you're working on a project where Prettier is not wanted it won't create unnecessarily **huge** file diffs. If this wasn't an option I wouldn't use Prettier as it's really annoying when you don't want it or it is not used among other developers on your team.
![image](https://user-images.githubusercontent.com/20328572/104074745-b7dc3000-51c5-11eb-92f9-aa717e139615.png)

Another extension I like is [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow). I would venture to say it shouldn't be opinionated as Prettier because it's more individual to the developer.

**Comment by codysmith287** [comment]
@Karvel Also is your list already somewhere in the S&P repo?

**Comment by Karvel** [comment]
> 
> 
> @Karvel Awesome list! I was just thinking of putting together a list of fairly nonopinionated and helpful extensions for Visual Studio exactly like this one.
> 
> What do you think about [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)?
> 
> I know Prettier is _pretty_ opinionated, but I like that it saves time and attention on formatting. It is lazy? Ehh... yeah, probably. A couple of things I would recommend one do if using Prettier in your Visual Studio Code settings would be:
> 
>     1. Have Prettier formatting run on each time you save a file rather than run as an npm script.
>        ![image](https://user-images.githubusercontent.com/20328572/104073934-c75a7980-51c3-11eb-8a40-a27ace8ed2ba.png)
> 
>     2. Have Prettier format **only** if a Prettier config file (`.prettierrc`) exists in the root directory of a project. That way if you're working on a project where Prettier is not wanted it won't create unnecessarily **huge** file diffs. If this wasn't an option I wouldn't use Prettier as it's really annoying when you don't want it or it is not used among other developers on your team.
>        ![image](https://user-images.githubusercontent.com/20328572/104074745-b7dc3000-51c5-11eb-92f9-aa717e139615.png)
> 
> 
> Another extension I like is [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow). I would venture to say it shouldn't be opinionated as Prettier because it's more individual to the developer.

I have started setting up prettier in my projects with a pre-commit hook. This enforces its styling project-wide. I don't actually like some of its styling, but I do like not having to think about style preferences anymore, or having to worry about constant style change deltas between individual editor settings. [Here is the PR](https://github.com/Shift3/boilerplate-client-angular/pull/197) where I added it to the Angular boilerplate. The process should basically be the same for any Javascript project using `npm`.

> @Karvel Also is your list already somewhere in the S&P repo? Thanks for sharing this as there were a few game changer extensions on your list that I didn't have.

Not at the moment, that's why I responded here! I have shared it in the mentoring slack channel. I originally created it for a new cohort sometime last year.
