### ISSUE TITLE
Code Reviews process does not mention adding pr-team as reviewers to your pull request

### ISSUE THREAD

**Issue by lizl714** [Shift3/standards-and-practices#244]
## Expected Behavior
Under Code Reviews - Process - Author - #2, the standards doc should mention that the author should always include the pr-team as potential reviewers (perhaps replacing all three bullets?)

## Actual/Current Behavior
Currently under Code Reviews - Process - Author - #2 it states the potential reviewers need to have three qualities (listed in bullets)

Per Corey:
Remove the three obsolete lines about who to add as a reviewer
Also:
Here would be some other items that might be useful to document:
A quick explanation of what pr-team is, and the fact that it will automatically replace the team with 3 auto-selected developers when the PR is submitted.
Mention that there are stack specific teams (devs-wordpress, devs-react, etc) which will also auto assign reviewers. These ones only assign 2 developers.
Explain the purpose of the pr-team and our approach on the review process:
Cross-team reviews encourage cross-training and knowledge sharing
PR reviewers are just as valuable as a learning opportunity for the reviewer as they are for the reviewee
Automatic assignment balances the workload evenly across the whole team
Everyone gets the opportunity to be both a reviewer and a reviewee
Pending PR reviews show up on the #shift3-code-review Slack channel as a notification and reminder. This has helped us develop a very quick turn-around on reviews.
Our standard code review process only requires a visual inspection of the code. Developers are not required to pull down and run/test the code. That said, project teams can add their own functional review process within the team in addition to the standard cross-team visual review.

**Comment by michaelachrisco** [comment]
@lizl714 thanks for the call out on that page. We do need to be a bit more clear on which team should be assigned per project. 

We actually have many different teams which include:
* devs-angular
* devs-django
* devs-dotnet
* devs-nativescript
* devs-node
* devs-react
* devs-react-native
* devs-wordpress
* PR Team

I personally think any of these teams are valid when it comes to reviewing the code. But im wondering if we want to make it a hard requirement that the PR Team is ALWAYS included on every pull request. I think this deserves a discussion.

**Comment by Karvel** [comment]
I just tried adding both pr-team and devs-angular on a PR. Between the two, it tagged 5 people (3 from pr-team, 2 from devs-angular).

**Comment by michaelachrisco** [comment]
I just did some internal testing and found that including two or more teams just increased the number of reviewers. I would rather GitHub allow for people that were in both teams to comment and limit the number of reviewers...

We may need to do some research on the best approach here. If anyone has any suggestions, let us know!

**Comment by thomwise** [comment]
Should I cancel my PR request on this issue then until we have more clarity then?

**Comment by michaelachrisco** [comment]
Nope your good! Ill ask in general chat and see what people think.

**Comment by kmausolf** [comment]
> I just did some internal testing and found that including two or more teams just increased the number of reviewers. I would rather GitHub allow for people that were in both teams to comment and limit the number of reviewers...
> 
> We may need to do some research on the best approach here. If anyone has any suggestions, let us know!

Given that `devs-<technology>` is a subset of `pr-team`, I would suggest just tagging the `devs-<technology>` team if you want someone from that team to review it.  Is there a reason you'd want less reviewers?

**Comment by coreyshuman** [comment]
>But im wondering if we want to make it a hard requirement that the PR Team is ALWAYS included on every pull request.

My rule of thumb has been that pr-team is the default go-to, but in cases were a PR needs extra scrutiny or has extenuating circumstances, you can instead ping the appropriate team (or the both the dev-team and pr-team).

Examples of extenuating circumstances could be a really complex language-specific feature, work which delves into the depths of said framework, a massive refactor, or if you have questions or need special review specific to a framework's featureset. Just to name a few things which could happen.

One reason we don't want to overuse the devs-*stack teams is that they are a much smaller pool. If I'm working on a .NET app and only ping devs-dotnet, then that's basically just 6-ish people who are getting the full workload of my submissions.

That's all just my recommendations at the moment, I definitely want to hear from the rest of the team on this to see what has been working or not working well for them. It's always a good thing to keep refining and improving our process.

**Comment by fluturecode** [comment]
I think opening up PR review for the most amount of devs on our team is great, helps everyone see the other current projects, helps make us feel more uniform, familiarize with new stacks, etc...That being said, this assumes that you already have enough people assigned to the PR with proper working knowledge to test that app. Must be the right combination of both so nothing slips through the cracks, while also allowing new team members to broaden their scope.

**Comment by ayojackay** [comment]
120% of what @fluturecode said. Personally, I feel there is more growth when exposed to other PR reviews on dev teams/projects you're not on. This exposure can help a dev grow, learn new things, and possibly catch a potential bug slipping by that two pairs of eyes missed. In the past, when I was tagged in a PR, I wholeheartedly admit that I wasn't on time to help approve a PR, so I barely approved any, but I sure was lurking after to see how that dev tackled or constructed their work of art in the matter.
Maybe a system can be set in a place where devs are broken into PR teams that are mixed with junior, advanced(is that a thing?), and senior devs who review PR's for a certain amount of time and then cycle through teams, so EVERYONE has a piece of the pie. The suggestion may be silly, but hey, it's a thought! 
@coreyshuman @michaelachrisco

**Comment by thomwise** [comment]
I like the thought of that idea @ayojackay, being new to the team and having seen and reviewed mostly WordPress code up until this point, if I am asked to give review on code based in React I don't know it, but I would love to see constructive examples of others reviewing that code. I feel like I would learn a lot from that.

**Comment by ryekerjh** [comment]
I don't love the idea of these blanket assignments, and I like that we have separate teams for each stack. I would say it should be required to add your stack team to your PRs, and then if those are not available or there isn't one for your stack, you should tag the whole team.

**Comment by coreyshuman** [comment]
@ryekerjh thank you for the honest feedback, I'd love to hear more about why you don't like the automated assignments. Can you go into detail about issues it has caused or challenges you've faced with this system?

I want to list some tangible improvements this system has made to our operations which we should keep in mind. That way if we choose to modify the system, we make sure to not lose these wins it has brought us.

- The workload has become much more even across the team. Before automated assignments, the persons doing the most reviews were performing a good 20x more reviews than the average. Nowadays looking at the last 8 months, the busiest reviewers are down to 5x above average, while the median has increased substantially.
- Average turnaround time for reviews has dropped below 12 hours, not counting weekends. 2-3 days or greater PR blocks were really common before that, but extremely rare now.
- More anecdotal, but the dev team is getting a lot more exposure to other stacks and other experienced dev reviews than before. Given that most of our project teams are 1-2 persons per project, and our Django and .NET stacks only have 6-ish devs each, this has really promoted cross-training and broken down the proverbial walls between all our teams.

Going back to my previous comment, I just remember another rule-of-thumb to add to my list:
- If you're assigned to a PR where you are truly uncomfortable or unable to provide feedback, no problem. Just let the author know so they can request more reviewers.

**Comment by coreyshuman** [comment]
It's important to add, this is not meant as a be-all, end-all process. This is just the bare minimum standard for project teams to apply. Then the individual teams can apply whatever additional process to their project that they find necessary and agree upon. 

So for example, if I was leading a project I could coordinate with my team on a procedure such as this (just an example):
- Follow the standard and ping pr-team
- Ping the appropriate stack team (let's say devs-angular)
- Ping a dev who is on the project, this person pulls down the code and runs it
- At least one internal and one external approval required to merge (2 approval minimum)

I wouldn't want to apply a global policy like the above example because that is _a lot_. But an individual team who is worried about review quality/consistency could totally agree to go for a stricter process.

This goes along with my goal to keep standards lightweight, and encourage individual teams to really define processes that work for them.

**Comment by kmausolf** [comment]
@coreyshuman It's good to define an ideal situation in the standard for this, but it is indeed a lot.  Very helpful, but not always feasible.  Focusing on what the "bare minimum" means for requesting review is also important so that we don't run into those situations where there's a PR sitting for half a week.

My suggestion for the bare minimum is:

- Always tag `pr-team`
- Tag the other developer(s) on the project

Although I'm not always able to provide the most informed feedback on PRs whose stack I am unfamiliar with, but I do appreciate getting a chance to see how people work in other stacks.  That's why I'm in support of always tagging `pr-team`.

**Comment by michaelachrisco** [comment]
Ive left this alone for a bit to see what experiences others have had with our pr process. We got some excellent feedback. Thanks everyone! I didnt realize this could be as complicated as it turned out to be.

I agree with @kmausolf that making sure the `pr-team` is at the very least tagged on each project. This seems to have helped with throughput and cross-platform training.
I appreciate @ryekerjh's perspective that we should avoid blanket assignments. We should be careful on hard setting any one team unless the project needs it (like a specific .net project needing the `devs-dotnet` team tagged).

Personally, I think we should try and make the instructions as simple as possible for now and see how this effects the organization. For now, just making sure the `pr-team` is always tagged should help with throughput and review time as we have seen in the last two quarters. How would everyone feel about leaving it up to the developers and/or team lead per project to include other teams at this time? I think that would be a good compromise for now.


@thomwise how would you feel if we also added @coreyshuman's amendment to the current PR?
`If you're assigned to a PR where you are truly uncomfortable or unable to provide feedback, no problem. Just let the author know so they can request more reviewers.`
If we are looking at review time, we should always try to make sure PRs are getting reviewed in a timely manner and I think more communication would not hurt the current process.

**Comment by coreyshuman** [comment]
@michaelachrisco I like the proposed solution! 

I would like to slightly adjust my comment if we plan to include it in the standard:
> If you're assigned to a PR in which you are uncomfortable or unable to approve or request changes, that is not a problem. It is completely acceptable to provide a comment-only review. Provide any feedback you can and then **make sure to let the author know** you are unable to approve so that they can request additional reviewers.

**Comment by thomwise** [comment]
Right on everyone! I will add this to the updates in the documentation and send out a PR (requesting the correct people hopefully) haha.
